### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by Claudio-Sjo** [michaelfranzl/rpi23-gen-image#1]
Hi Michael,
I'm trying to use the tool and met some issues:
1. Minor : git is not part of default debian installation, it must be manually added by means of apt
2. Major : the instructions are not working with all vanilla kernels, it should be stated a way for fetching the correct version that will work, or at least one of the version that you verified. In the instructions you specify what version was, but not how to fetch that version. 

Thanks for your effort.
/Claudio

**Comment by Claudio-Sjo** [comment]
Sorry, it was my fault and my browser's also...
git dependency is specified!

**Comment by michaelfranzl** [comment]
There are many good tutorials about git, but it is rather simple: `git checkout {revision}`.

**Comment by michaelfranzl** [comment]
I added the commands to the README tutorial.
