### ISSUE TITLE
APT_PROXY empty value

### ISSUE THREAD

**Issue by Lesik** [michaelfranzl/rpi23-gen-image#10]
Hey,

I use no proxy to connect to the internet, and according to the README the proxy is unset by default. However, `10-bootstrap.sh` still fails:
```
+ http_proxy=localhost:3142 debootstrap --arch=arm64 [...]
I: Retrieving InRelease 
I: Retrieving Release 
E: Failed getting release file http://ftp.debian.org/debian/dists/stretch/Release
```

Notice the `http_proxy` being set. So I try to overwrite the proxy by setting `APT_PROXY=""`, but that doesn't help either, because of [this line](https://github.com/michaelfranzl/rpi23-gen-image/blob/master/rpi23-gen-image.sh#L85):

```
APT_PROXY=${APT_PROXY:="localhost:3142"}
```

If `APT_PROXY` is set but empty, it will be still set to localhost:3142. Check out this simplified example:
```
$ myvar=""
$ othervar=${myvar:="notempty"}
$ echo $othervar
notempty
```

**Comment by nwildner** [comment]
Maybe this proxy variable is enforced cause the instructions suggest you to install `apt-cache-ng`

https://github.com/michaelfranzl/rpi23-gen-image#set-up-caching-for-apt

It is zero configuration as this readme states. Install apt-proxy-ng to make localcache of all packages downloaded, so you dont have get all again whenever you need to create a new image,.

**Comment by Lesik** [comment]
Yes, I read the README. But I do not want to use `apt-cache-ng`.

And [this line](https://github.com/michaelfranzl/rpi23-gen-image#apt_proxy):
```
APT_PROXY=""
```
seems to suggest that if I leave the variable empty, the default value will be `""`.

**Comment by paulghill** [comment]
Edit the rpi23-gen-image.sh and look for APT_PROXY and change it to as follows:  APT_PROXY=${APT_PROXY:=""}

**Comment by Lesik** [comment]
I fixed this for myself the second I found the bug. The point of this bug report is that it's fixed for others who may not want/be able to read (ba)sh.
