### ISSUE TITLE
WiFi not available on RasPi3 b with Stretch + 4.10 vanilla

### ISSUE THREAD

**Issue by bneuburg** [michaelfranzl/rpi23-gen-image#2]
Hi,

I succesfully built an image and my Raspberry Pi 3 boots up. However `ip l` only lists `lo` and `eth0`, no WiFi adapter. `modprobe brcmfmac` does not improve the situation. 

I used the 4.10 kernel as described in the README and the `working-rpi3-linux-config.txt` and modified it to include NFTables support.

The command line to build the image was:
```
DEBIAN_RELEASE="stretch" USER_NAME="pi" PASSWORD="randompass" \
 APT_INCLUDES="i2c-tools,rng-tools,avahi-daemon,rsync,sudo,psutils" \ 
 UBOOTSRC_DIR="$(pwd)/../u-boot" KERNELSRC_DIR="$(pwd)/../linux" RPI_MODEL=3 \ 
 HOSTNAME="rpi3" RPI_FIRMWARE_DIR="$(pwd)/../raspberry-firmware" ENABLE_IPTABLES=true \
 ENABLE_REDUCE=false ENABLE_WIRELESS=true REDUCE_SSHD=false ./rpi23-gen-image.sh
```

Am I missing something? What do I need to modprobe?

**Comment by michaelfranzl** [comment]
I haven't tested WiFi on the RPi3 yet. I'll leave this issue open in case someone finds a solution.

**Comment by bneuburg** [comment]
If dmesg doesn't return anything regarding mmc1 but only mentions mmc0 might that be related to the problem?

**Comment by purbo** [comment]
please check [https://github.com/Fourdee/DietPi/issues/475#issuecomment-270696515](https://github.com/Fourdee/DietPi/issues/475#issuecomment-270696515)

**Comment by D-Albers** [comment]
I have had the same problem and changed back to the Foundation kernel.

**Comment by andrewkress** [comment]
is it kernel related, or driver related?  I attempted with the 4.11.1 kernel and no wifi recognized.

**Comment by michaelfranzl** [comment]
The kernel is the driver. Getting all the hardware features working is not part of my rpi23-gen-image fork. If you need all hardware supported, you will have to switch to the Raspberry kernel, or wait until the hardware support has been upstreamed into the official Linux kernel.

**Comment by andrewkress** [comment]
Your documentation states that this script doesn't work for the raspberry kernel.  Is there a specific reason i can't build to the raspberry kernel the same way that I would build the vanilla kernel from source?

**Comment by D-Albers** [comment]
I have compiled the foundation kernel with 
```
CROSS_COMPILE=aarch64-linux-gnu- ARCH=arm64 make bcmrpi3_defconfig
CROSS_COMPILE=aarch64-linux-gnu- ARCH=arm64 make Image dtbs modules
CROSS_COMPILE=aarch64-linux-gnu- ARCH=arm64 make modules_install
```
and execute the script.

If I remember right, there is a line which checks for a compiled kernel. This needs a fix to the kernel file name. (At the moment under windows without access to the project.)

**Comment by michaelfranzl** [comment]
To clarify, if you don't want to use the official Linux kernel and need full hardware support provided by the Raspberry Pi Foundation kernel, please consider using the original [rpi23-gen-image](https://github.com/drtyhlpr/rpi23-gen-image) script by drtyhlpr which uses the Raspberry Pi Foundation kernel. Remember that my project is just a fork of this other project, specializing on the official Linux kernel.

**Comment by michaelfranzl** [comment]
Setting ENABLE_WIRELESS works now. The hardcoded link to https://github.com/RPi-Distro/firmware-nonfree/tree/master/brcm was outdated. This has been fixed.
