### ISSUE TITLE
`Exec format error` when running `chroot_exec`

### ISSUE THREAD

**Issue by lennartS** [michaelfranzl/rpi23-gen-image#5]
First of all, thank you for this great script and the README. It made installing a stock Debian on the Pi3 a breeze. I ran into a small issue though but am not sure if it is related to the script or my specific scenario.

# Scenario
I created a chroot on my host machine (which is Debian unstable) to install Debian stretch x86_64 as basis for rpi23-gen-image. As such I only installed the packages that were mentioned in the Readme and did no further steps (besides what is done by `cdebootstrap` automatically).

# Actual behaviour
My first attempt of running `rpi23-gen-image.sh` (by way of a modified `example.sh`) an error was thrown by `chroot_exec` however, similar to the following one:

    chroot: failed to run command `/debootstrap/debootstrap': Exec format error

# Possible solution
A little googling brought me to the solution. When running `update-binfmts --display` it would show all installed toolchains(?) as `disabled`, even `qemu-aarch64`. I fixed this by running

    update-binfmts --enable qemu-aarch64

After that `rpi23-gen-image.sh` finished through without problem.

**Comment by michaelfranzl** [comment]
Yes, "Exec format error" indicates a problem with qemu. It may have to do with Debian unstable vs. stretch. Did you execute `update-binfmts` in the host environment or in the chroot?

**Comment by lennartS** [comment]
I had to run `update-binfmts` in the Debian stretch chroot used to run `rpi23-gen-image.sh`. In my Debian unstable host environment `qemu-user-static` is not installed.

**Comment by lennartS** [comment]
Oh, I forgot to mention: The stretch chroot is x86_64.

**Comment by amanharitsh123** [comment]
here i got this error update-binfmts: warning: Couldn't load the binfmt_misc module. when i run update-binfmts 
I am using debian stretch using schroot on my ubuntu 16.04.
